// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: meta/meta.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Flipt.Meta {

  /// <summary>Holder for reflection information generated from meta/meta.proto</summary>
  public static partial class MetaReflection {

    #region Descriptor
    /// <summary>File descriptor for meta/meta.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MetaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg9tZXRhL21ldGEucHJvdG8SCmZsaXB0Lm1ldGEaGWdvb2dsZS9hcGkvaHR0",
            "cGJvZHkucHJvdG8aG2dvb2dsZS9wcm90b2J1Zi9lbXB0eS5wcm90bzKQAQoP",
            "TWV0YWRhdGFTZXJ2aWNlEkIKEEdldENvbmZpZ3VyYXRpb24SFi5nb29nbGUu",
            "cHJvdG9idWYuRW1wdHkaFC5nb29nbGUuYXBpLkh0dHBCb2R5IgASOQoHR2V0",
            "SW5mbxIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoULmdvb2dsZS5hcGkuSHR0",
            "cEJvZHkiAEIiWiBnby5mbGlwdC5pby9mbGlwdC9ycGMvZmxpcHQvbWV0YWIG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.HttpbodyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
