// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: gnostic/openapi/v3/annotations.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Gnostic.Openapi.V3 {

  /// <summary>Holder for reflection information generated from gnostic/openapi/v3/annotations.proto</summary>
  public static partial class AnnotationsReflection {

    #region Descriptor
    /// <summary>File descriptor for gnostic/openapi/v3/annotations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AnnotationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRnbm9zdGljL29wZW5hcGkvdjMvYW5ub3RhdGlvbnMucHJvdG8SEmdub3N0",
            "aWMub3BlbmFwaS52MxoiZ25vc3RpYy9vcGVuYXBpL3YzL29wZW5hcGl2My5w",
            "cm90bxogZ29vZ2xlL3Byb3RvYnVmL2Rlc2NyaXB0b3IucHJvdG86VwoIZG9j",
            "dW1lbnQSHC5nb29nbGUucHJvdG9idWYuRmlsZU9wdGlvbnMY9wggASgLMhwu",
            "Z25vc3RpYy5vcGVuYXBpLnYzLkRvY3VtZW50Ughkb2N1bWVudDpcCglvcGVy",
            "YXRpb24SHi5nb29nbGUucHJvdG9idWYuTWV0aG9kT3B0aW9ucxj3CCABKAsy",
            "HS5nbm9zdGljLm9wZW5hcGkudjMuT3BlcmF0aW9uUglvcGVyYXRpb246VAoG",
            "c2NoZW1hEh8uZ29vZ2xlLnByb3RvYnVmLk1lc3NhZ2VPcHRpb25zGPcIIAEo",
            "CzIaLmdub3N0aWMub3BlbmFwaS52My5TY2hlbWFSBnNjaGVtYTpWCghwcm9w",
            "ZXJ0eRIdLmdvb2dsZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMY9wggASgLMhou",
            "Z25vc3RpYy5vcGVuYXBpLnYzLlNjaGVtYVIIcHJvcGVydHlCWgoOb3JnLm9w",
            "ZW5hcGlfdjNCEEFubm90YXRpb25zUHJvdG9QAVouZ2l0aHViLmNvbS9nb29n",
            "bGUvZ25vc3RpYy9vcGVuYXBpdjM7b3BlbmFwaV92M6ICA09BU2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Gnostic.Openapi.V3.Openapiv3Reflection.Descriptor, global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { AnnotationsExtensions.Document, AnnotationsExtensions.Operation, AnnotationsExtensions.Schema, AnnotationsExtensions.Property }, null));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of gnostic/openapi/v3/annotations.proto</summary>
  public static partial class AnnotationsExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Gnostic.Openapi.V3.Document> Document =
      new pb::Extension<global::Google.Protobuf.Reflection.FileOptions, global::Gnostic.Openapi.V3.Document>(1143, pb::FieldCodec.ForMessage(9146, global::Gnostic.Openapi.V3.Document.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Gnostic.Openapi.V3.Operation> Operation =
      new pb::Extension<global::Google.Protobuf.Reflection.MethodOptions, global::Gnostic.Openapi.V3.Operation>(1143, pb::FieldCodec.ForMessage(9146, global::Gnostic.Openapi.V3.Operation.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Gnostic.Openapi.V3.Schema> Schema =
      new pb::Extension<global::Google.Protobuf.Reflection.MessageOptions, global::Gnostic.Openapi.V3.Schema>(1143, pb::FieldCodec.ForMessage(9146, global::Gnostic.Openapi.V3.Schema.Parser));
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Gnostic.Openapi.V3.Schema> Property =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, global::Gnostic.Openapi.V3.Schema>(1143, pb::FieldCodec.ForMessage(9146, global::Gnostic.Openapi.V3.Schema.Parser));
  }

}

#endregion Designer generated code
