// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: evaluation/evaluation.proto
// </auto-generated>
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Flipt.Evaluation {
  public static partial class EvaluationService
  {
    static readonly string __ServiceName = "flipt.evaluation.EvaluationService";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Flipt.Evaluation.EvaluationRequest> __Marshaller_flipt_evaluation_EvaluationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Flipt.Evaluation.EvaluationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Flipt.Evaluation.BooleanEvaluationResponse> __Marshaller_flipt_evaluation_BooleanEvaluationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Flipt.Evaluation.BooleanEvaluationResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Flipt.Evaluation.VariantEvaluationResponse> __Marshaller_flipt_evaluation_VariantEvaluationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Flipt.Evaluation.VariantEvaluationResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Flipt.Evaluation.BatchEvaluationRequest> __Marshaller_flipt_evaluation_BatchEvaluationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Flipt.Evaluation.BatchEvaluationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Flipt.Evaluation.BatchEvaluationResponse> __Marshaller_flipt_evaluation_BatchEvaluationResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Flipt.Evaluation.BatchEvaluationResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.BooleanEvaluationResponse> __Method_Boolean = new grpc::Method<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.BooleanEvaluationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Boolean",
        __Marshaller_flipt_evaluation_EvaluationRequest,
        __Marshaller_flipt_evaluation_BooleanEvaluationResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.VariantEvaluationResponse> __Method_Variant = new grpc::Method<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.VariantEvaluationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Variant",
        __Marshaller_flipt_evaluation_EvaluationRequest,
        __Marshaller_flipt_evaluation_VariantEvaluationResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Flipt.Evaluation.BatchEvaluationRequest, global::Flipt.Evaluation.BatchEvaluationResponse> __Method_Batch = new grpc::Method<global::Flipt.Evaluation.BatchEvaluationRequest, global::Flipt.Evaluation.BatchEvaluationResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Batch",
        __Marshaller_flipt_evaluation_BatchEvaluationRequest,
        __Marshaller_flipt_evaluation_BatchEvaluationResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Flipt.Evaluation.EvaluationReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of EvaluationService</summary>
    [grpc::BindServiceMethod(typeof(EvaluationService), "BindService")]
    public abstract partial class EvaluationServiceBase
    {
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Flipt.Evaluation.BooleanEvaluationResponse> Boolean(global::Flipt.Evaluation.EvaluationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Flipt.Evaluation.VariantEvaluationResponse> Variant(global::Flipt.Evaluation.EvaluationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Flipt.Evaluation.BatchEvaluationResponse> Batch(global::Flipt.Evaluation.BatchEvaluationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for EvaluationService</summary>
    public partial class EvaluationServiceClient : grpc::ClientBase<EvaluationServiceClient>
    {
      /// <summary>Creates a new client for EvaluationService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EvaluationServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for EvaluationService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EvaluationServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EvaluationServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EvaluationServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.BooleanEvaluationResponse Boolean(global::Flipt.Evaluation.EvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Boolean(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.BooleanEvaluationResponse Boolean(global::Flipt.Evaluation.EvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Boolean, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.BooleanEvaluationResponse> BooleanAsync(global::Flipt.Evaluation.EvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BooleanAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.BooleanEvaluationResponse> BooleanAsync(global::Flipt.Evaluation.EvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Boolean, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.VariantEvaluationResponse Variant(global::Flipt.Evaluation.EvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Variant(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.VariantEvaluationResponse Variant(global::Flipt.Evaluation.EvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Variant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.VariantEvaluationResponse> VariantAsync(global::Flipt.Evaluation.EvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return VariantAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.VariantEvaluationResponse> VariantAsync(global::Flipt.Evaluation.EvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Variant, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.BatchEvaluationResponse Batch(global::Flipt.Evaluation.BatchEvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Batch(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Flipt.Evaluation.BatchEvaluationResponse Batch(global::Flipt.Evaluation.BatchEvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Batch, null, options, request);
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.BatchEvaluationResponse> BatchAsync(global::Flipt.Evaluation.BatchEvaluationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return BatchAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Flipt.Evaluation.BatchEvaluationResponse> BatchAsync(global::Flipt.Evaluation.BatchEvaluationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Batch, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override EvaluationServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EvaluationServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(EvaluationServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Boolean, serviceImpl.Boolean)
          .AddMethod(__Method_Variant, serviceImpl.Variant)
          .AddMethod(__Method_Batch, serviceImpl.Batch).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EvaluationServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Boolean, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.BooleanEvaluationResponse>(serviceImpl.Boolean));
      serviceBinder.AddMethod(__Method_Variant, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Flipt.Evaluation.EvaluationRequest, global::Flipt.Evaluation.VariantEvaluationResponse>(serviceImpl.Variant));
      serviceBinder.AddMethod(__Method_Batch, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Flipt.Evaluation.BatchEvaluationRequest, global::Flipt.Evaluation.BatchEvaluationResponse>(serviceImpl.Batch));
    }

  }
}
#endregion
